version: "3.9"
services:
  icv_app:
    image: omagdy/icv:dev
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - input:/app/input
      - output:/app/output
volumes:
  input:
  output:
